add timeout to new_command_available check
planckaero/ardupilot pull request #42
Opened 2021-08-27 23:23 UTC by CraftyJax

This PR adds a timeout to the new_command_available() check in AC_Planck. Specifically, it sets _cmd.is_new = false if the timestamp of _cmd is older than 100 ms. 

Addresses https://planckaero.atlassian.net/browse/ACE-965 and partially helps with https://planckaero.atlassian.net/browse/ACE-976

2021-08-30 19:09 UTC, almatthew requested changes
@CraftyJax I think this is good but I'm not sure it actually solves the problem, i.e. it doesn't overwrite any existing "latched" GUIDED mode commands?

2021-08-30 20:20 UTC, CraftyJax commented
@almatthew Since new_command_available is called whenver "_cmd" is read, it prevents a stale "_cmd" from ever being used. This definitely solves the issue in sim.

2021-08-30 20:22 UTC, almatthew commented
> @almatthew Since new_command_available is called whenver "_cmd" is read, it prevents a stale "_cmd" from ever being used. This definitely solves the issue in sim.

I see, but it doesn't solve the "NO_COMMAND" issue where APM latches to the last ACE command (example: Saitotec), right?

2021-09-01 16:11 UTC, CraftyJax commented
@almatthew I've made some additions to this PR so it now handles the "NO_COMMAND" problem

2021-09-01 20:37 UTC, AubreyC approved these changes
looks good 👍

2021-09-21 21:47 UTC, almatthew requested changes

2021-09-21 21:47 UTC, almatthew commented on ArduCopter/mode_plancktracking.cpp
> +        if(should_reset_update_times())
since `reset_update_times()` should only be called if `should_reset_update_times()` returns true, why not just combine them into a single method that checks whether or not it should reset them prior to resetting them?

2021-09-21 21:57 UTC, CraftyJax commented on ArduCopter/mode_plancktracking.cpp
> +        if(should_reset_update_times())
My thought was for clarity - calling reset_update_times() would always reset them, no ambiguity. Someone down the line could call it, not expecting it to do nothing. Think it's better to  reduce to one?

2021-09-21 21:58 UTC, almatthew commented on ArduCopter/mode_plancktracking.cpp
> +        if(should_reset_update_times())
I guess the question is: what case would want to reset them without checking?

2021-09-21 22:00 UTC, CraftyJax commented on ArduCopter/mode_plancktracking.cpp
> +        if(should_reset_update_times())
Maybe if someone want to do some kind of force init/reset on the whole thing?

2021-09-21 22:02 UTC, CraftyJax commented on ArduCopter/mode_plancktracking.cpp
> +        if(should_reset_update_times())
Easy enough to make the change though, so if we don't care about the modularity I'll go ahead and combine them

2021-09-21 22:34 UTC, almatthew approved these changes

2022-05-06 16:06 UTC, CraftyJax commented
Identical changes are in PR https://github.com/planckaero/ardupilot/pull/49, closing

2022-05-06 16:06 UTC, closed without merging